### PR TITLE
added pipenv files, fixed hardcoded paths

### PR DESCRIPTION
**Pull request by udnaan**
This fixes hardcoded paths. Also adds pipenv files for pythonic virtualenv based install.

### CODE REVIEW

**Comment by yuanming-hu** [comment]
I will likely approve the whole PR. Just need a bit more time to think about how taichi should be shipped with pip, and how should it interact with pipenv :-)

**Comment by udnaan** [comment]
Alright. Take your time.

**Comment by yuanming-hu** [comment]
After reading https://pipenv.readthedocs.io/en/latest/advanced/#pipfile-vs-setup-py, I think since `taichi` is a library that other applications should depend on, it seems more reasonable to me to have a `setup.py` file and release it with `pip` (though currently I haven't done so, sorry). The pipfile approach is preferred for an application that is built upon `taichi`. What do you think?

**Comment by yuanming-hu** [comment]
I think we should still take the pipenv approach, to ease the life of developers. It is always good to have locked versions of dependencies to for bug reproducibility if doing so does not bring us too much complexity. For end-users, I will spend some time and make a setup.py and release it on pip.

**Comment by udnaan** [comment]
Regarding the setup.py, that would be great!
For now, just having a pipfile that lists the dependencies is a good start.

**Comment by yuanming-hu** [comment]
Sounds good! Thanks!

**Pull request merged**
